doctrine_migrations:
    migrations_paths:
        'Twitter\IAM\Infrastructure\Persistence\MySQL\Migrations': '%kernel.project_dir%/src/IAM/Infrastructure/Persistence/MySQL/Migrations'
    enable_profiler: false
