doctrine_migrations:
    migrations_paths:
        'Twitter\IAM\Infrastructure\Persistence\MySQL\Migration': '%kernel.project_dir%/src/IAM/Infrastructure/Persistence/MySQL/Migration'
    enable_profiler: false
