# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

api_health:
    path: /api/health
    controller: Twitter\Health\UI\REST\Controller\HealthController
    methods: GET
