# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

health_check_module:
    resource: ../src/HealthCheck/Controller/HealthCheckController.php
    type: attribute

api_users_create:
    path: /api/users
    controller: Twitter\IAM\UI\REST\Controller\CreateUserController
    methods: POST
