# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

health_check_module:
    resource: ../src/HealthCheck/Controller/HealthCheckController.php
    type: attribute
    
api_create_user:
    resource: ../src/IAM/UI/REST/Controller/CreateUserController.php
    type: attribute
    
api_create_profile:
    resource: ../src/Profile/UI/REST/Controller/CreateProfile/CreateProfileController.php
    type: attribute
